name: Replace App Icons with Custom Logo

on:
  workflow_dispatch:
    inputs:
      logo:
        description: "Path to the custom logo image"
        required: true
        default: "custom-logo.png"  # Specify the path to your logo

jobs:
  replace-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ImageMagick and Unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick unzip zip

      - name: Unzip assets
        run: unzip Assets.zip -d assets

      - name: Replace images with custom logo
        run: |
          # Replace each image in Assets.zip with resized versions of the custom logo
          convert ${{ github.event.inputs.logo }} -resize 310x150 -depth 32 assets/Wide310x150Logo.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 620x300 -depth 32 assets/Wide310x150Logo.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 1240x600 -depth 32 assets/Wide310x150Logo.scale-400.png

          convert ${{ github.event.inputs.logo }} -resize 150x150 -depth 32 assets/Square150x150Logo.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 300x300 -depth 32 assets/Square150x150Logo.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 600x600 -depth 32 assets/Square150x150Logo.scale-400.png

          convert ${{ github.event.inputs.logo }} -resize 44x44 -depth 32 assets/Square44x44Logo.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 88x88 -depth 32 assets/Square44x44Logo.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 176x176 -depth 32 assets/Square44x44Logo.scale-400.png

          convert ${{ github.event.inputs.logo }} -resize 16x16 -depth 32 assets/Square44x44Logo.altform-unplated_targetsize-16.png
          convert ${{ github.event.inputs.logo }} -resize 256x256 -depth 32 assets/Square44x44Logo.altform-unplated_targetsize-256.png
          convert ${{ github.event.inputs.logo }} -resize 48x48 -depth 32 assets/Square44x44Logo.altform-unplated_targetsize-48.png

          convert ${{ github.event.inputs.logo }} -resize 16x16 -depth 32 assets/Square44x44Logo.targetsize-16.png
          convert ${{ github.event.inputs.logo }} -resize 256x256 -depth 32 assets/Square44x44Logo.targetsize-256.png
          convert ${{ github.event.inputs.logo }} -resize 48x48 -depth 32 assets/Square44x44Logo.targetsize-48.png

          convert ${{ github.event.inputs.logo }} -resize 50x50 -depth 32 assets/StoreLogo.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 100x100 -depth 32 assets/StoreLogo.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 200x200 -depth 32 assets/StoreLogo.scale-400.png

          convert ${{ github.event.inputs.logo }} -resize 310x310 -depth 32 assets/LargeTile.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 620x620 -depth 32 assets/LargeTile.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 1240x1240 -depth 32 assets/LargeTile.scale-400.png

          convert ${{ github.event.inputs.logo }} -resize 150x150 -depth 32 assets/SmallTile.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 300x300 -depth 32 assets/SmallTile.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 600x600 -depth 32 assets/SmallTile.scale-400.png

          convert ${{ github.event.inputs.logo }} -resize 620x300 -depth 32 -background none -gravity center assets/SplashScreen.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 1240x600 -depth 32 -background none -gravity center assets/SplashScreen.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 2480x1200 -depth 32 -background none -gravity center assets/SplashScreen.scale-400.png

      - name: Repack into ZIP
        run: |
          cd assets
          zip -r ../Updated_Assets.zip .

      - name: Upload updated ZIP as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Updated_Assets
          path: Updated_Assets.zip