name: Replace App Icons with Custom Logo

on:
  workflow_dispatch:
    inputs:
      logo:
        description: "Path to the custom logo image"
        required: true
        default: "custom-logo.png"

jobs:
  replace-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ImageMagick and Unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick unzip zip

      - name: Unzip assets
        run: unzip Assets.zip -d assets

      - name: Replace images with custom logo
        run: |
          # Replace each image with resized versions, enforcing exact sizes
          convert ${{ github.event.inputs.logo }} -resize 310x150 -extent 310x150 assets/Wide310x150Logo.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 388x188 -extent 388x188 assets/Wide310x150Logo.scale-125.png
          convert ${{ github.event.inputs.logo }} -resize 465x225 -extent 465x225 assets/Wide310x150Logo.scale-150.png
          convert ${{ github.event.inputs.logo }} -resize 620x300 -extent 620x300 assets/Wide310x150Logo.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 1240x600 -extent 1240x600 assets/Wide310x150Logo.scale-400.png

          convert ${{ github.event.inputs.logo }} -resize 150x150 -extent 150x150 assets/Square150x150Logo.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 188x188 -extent 188x188 assets/Square150x150Logo.scale-125.png
          convert ${{ github.event.inputs.logo }} -resize 225x225 -extent 225x225 assets/Square150x150Logo.scale-150.png
          convert ${{ github.event.inputs.logo }} -resize 300x300 -extent 300x300 assets/Square150x150Logo.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 600x600 -extent 600x600 assets/Square150x150Logo.scale-400.png

          convert ${{ github.event.inputs.logo }} -resize 44x44 -extent 44x44 assets/Square44x44Logo.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 55x55 -extent 55x55 assets/Square44x44Logo.scale-125.png
          convert ${{ github.event.inputs.logo }} -resize 66x66 -extent 66x66 assets/Square44x44Logo.scale-150.png
          convert ${{ github.event.inputs.logo }} -resize 88x88 -extent 88x88 assets/Square44x44Logo.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 176x176 -extent 176x176 assets/Square44x44Logo.scale-400.png

          convert ${{ github.event.inputs.logo }} -resize 16x16 -extent 16x16 assets/Square44x44Logo.targetsize-16.png
          convert ${{ github.event.inputs.logo }} -resize 24x24 -extent 24x24 assets/Square44x44Logo.targetsize-24.png
          convert ${{ github.event.inputs.logo }} -resize 32x32 -extent 32x32 assets/Square44x44Logo.targetsize-32.png
          convert ${{ github.event.inputs.logo }} -resize 48x48 -extent 48x48 assets/Square44x44Logo.targetsize-48.png
          convert ${{ github.event.inputs.logo }} -resize 256x256 -extent 256x256 assets/Square44x44Logo.targetsize-256.png

          convert ${{ github.event.inputs.logo }} -resize 50x50 -extent 50x50 assets/StoreLogo.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 63x63 -extent 63x63 assets/StoreLogo.scale-125.png
          convert ${{ github.event.inputs.logo }} -resize 75x75 -extent 75x75 assets/StoreLogo.scale-150.png
          convert ${{ github.event.inputs.logo }} -resize 100x100 -extent 100x100 assets/StoreLogo.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 200x200 -extent 200x200 assets/StoreLogo.scale-400.png

          convert ${{ github.event.inputs.logo }} -resize 310x310 -extent 310x310 assets/LargeTile.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 388x388 -extent 388x388 assets/LargeTile.scale-125.png
          convert ${{ github.event.inputs.logo }} -resize 465x465 -extent 465x465 assets/LargeTile.scale-150.png
          convert ${{ github.event.inputs.logo }} -resize 620x620 -extent 620x620 assets/LargeTile.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 1240x1240 -extent 1240x1240 assets/LargeTile.scale-400.png

          convert ${{ github.event.inputs.logo }} -resize 71x71 -extent 71x71 assets/SmallTile.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 89x89 -extent 89x89 assets/SmallTile.scale-125.png
          convert ${{ github.event.inputs.logo }} -resize 107x107 -extent 107x107 assets/SmallTile.scale-150.png
          convert ${{ github.event.inputs.logo }} -resize 142x142 -extent 142x142 assets/SmallTile.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 284x284 -extent 284x284 assets/SmallTile.scale-400.png

          convert ${{ github.event.inputs.logo }} -resize 620x300 -extent 620x300 -background none -gravity center assets/SplashScreen.scale-100.png
          convert ${{ github.event.inputs.logo }} -resize 775x375 -extent 775x375 -background none -gravity center assets/SplashScreen.scale-125.png
          convert ${{ github.event.inputs.logo }} -resize 930x450 -extent 930x450 -background none -gravity center assets/SplashScreen.scale-150.png
          convert ${{ github.event.inputs.logo }} -resize 1240x600 -extent 1240x600 -background none -gravity center assets/SplashScreen.scale-200.png
          convert ${{ github.event.inputs.logo }} -resize 2480x1200 -extent 2480x1200 -background none -gravity center assets/SplashScreen.scale-400.png

      - name: Repack into ZIP
        run: |
          cd assets
          zip -r ../Updated_Assets.zip .

      - name: Upload updated ZIP as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Updated_Assets
          path: Updated_Assets.zip
